#!/usr/bin/env bash
# Create config/cole.env from GitHub repo variable (requires gh auth + repo access).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO="${LEARNING_KB_GH_REPO:-KeyFlo-ai/knowledge-base}"
OUT="${ROOT}/config/cole.env"

if ! command -v gh >/dev/null; then
  echo "error: install GitHub CLI (gh) and run: gh auth login" >&2
  exit 1
fi

TOKEN="$(gh variable get LEARNING_KB_API_TOKEN -R "$REPO" 2>/dev/null || true)"
if [[ -z "$TOKEN" ]]; then
  echo "error: LEARNING_KB_API_TOKEN not set on $REPO (ask James to run sync-knowledge-base-gh-secrets.sh)" >&2
  exit 1
fi

cat > "$OUT" <<EOF
# Generated by scripts/setup-cole-env.sh — gitignored
LEARNING_KB_API_URL=https://kb-api.keyflo.ai
LEARNING_KB_API_TOKEN=${TOKEN}
EOF
chmod 600 "$OUT"
echo "Wrote $OUT"
echo "Run: source config/cole.env && python scripts/query_api.py \"your question\""
